server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                use_sql_comments: true

jwt:
  signerKey: "MAOAaDeZDPe7abJfyyYmg6G4TQXTdQHNrGRFTdOr1whp6zdheS/COfx2GlDSMbXH"
  valid-duration: 3600
  refreshable-duration: 36000

cloudinary:
  cloud-name: dxjsjfevb
  api-key: 718915332696724
  api-secret: khXJ7CTZENe0voB1KRiR2VBr_6E

app:
  upload:
    max-file-size : 5MB
    allowed-extensions : jpg,jpeg,png,gif,webp